config/routes.rb
Rails.application.routes.draw do
  root to: 'frontend#index'

  get 'services', to: 'frontend#services'

  get 'team', to: 'frontend#team'

  get 'projects', to: 'frontend#projects'

  get 'contact_us', to: 'frontend#contact_us'

  get 'identity', to: 'frontend#identity'

  get 'web', to: 'frontend#web'

  get 'socials', to: 'frontend#socials'

  get 'blog', to: 'frontend#blog'

  devise_for :users, skip: KepplerConfiguration.skip_module_devise

  resources :admin, only: :index

  scope :admin do
    resources :users do
      get '(page/:page)', action: :index, on: :collection, as: ''
      delete(
        '/destroy_multiple',
        action: :destroy_multiple,
        on: :collection,
        as: :destroy_multiple
      )
    end

    resources :meta_tags do
      get '(page/:page)', action: :index, on: :collection, as: ''
      delete(
        '/destroy_multiple',
        action: :destroy_multiple,
        on: :collection,
        as: :destroy_multiple
      )
    end

    resources :google_adwords do
      get '(page/:page)', action: :index, on: :collection, as: ''
      delete(
        '/destroy_multiple',
        action: :destroy_multiple,
        on: :collection,
        as: :destroy_multiple
      )
    end

    resources :google_analytics_tracks do
      get '(page/:page)', action: :index, on: :collection, as: ''
      delete(
        '/destroy_multiple',
        action: :destroy_multiple,
        on: :collection,
        as: :destroy_multiple
      )
    end

    resources :settings, only: [] do
      collection do
        get '/:config', to: 'settings#edit', as: ''
        put '/:config', to: 'settings#update', as: 'update'
      end
    end
  end

  # Errors routes
  match '/403', to: 'errors#not_authorized', via: :all, as: :not_authorized
  match '/404', to: 'errors#not_found', via: :all
  match '/422', to: 'errors#unprocessable', via: :all
  match '/500', to: 'errors#internal_server_error', via: :all

  # Dashboard route engine
  mount KepplerGaDashboard::Engine, at: '/', as: 'dashboard'
end

app/views/layouts/admin/_head.html.haml
%head
  %meta{:name => "viewport", :content => "width=device-width, initial-scale=1.0"}
  %link{href:'http://fonts.googleapis.com/css?family=Patua+One', rel:'stylesheet', type:'text/css'}
  %title= content_for?(:title) ? yield(:title) : 'Keppler Admin'
  = stylesheet_link_tag 'admin/application', media: 'all', 'data-turbolinks-track' => true
  = javascript_include_tag 'admin/application', 'data-turbolinks-track' => true
  = csrf_meta_tags
  = favicon_link_tag "admin/favicon.png"

app/views/layouts/admin/_header.html.haml
.header-information.hide-on-small-only{ "ng-style" => listing? ? "{'max-width':'75%'}" : "{'min-width':'100%'}", class: "keppler-bg-1" }
	%h1 
		= content_for?(:header_information) ? yield(:header_information) : t("keppler.modules.#{controller_path.underscore}")
	%small 
		= t("keppler.actions.#{action_name}")

	

app/views/layouts/admin/_messages.html.haml
- flash.each do |name, msg|
	- if msg.is_a?(String)
		:javascript
			noty({
				text: "#{msg}", 
				layout: 'bottomRight',
				type: 'alert',
				dismissQueue: true,
				animation: {
					open: 'animated tada',
					close: 'bounceOutRight',
					easing: 'swing',
					speed: 500 },
				timeout: 5000,
				callback: {
					afterShow: 
						function() {
							$.noty.closeAll()
						}
				}
			});
			

app/views/layouts/admin/_navigation.html.haml
.navbar-fixed{ "ng-style" => listing? ? "{'max-width':'75%'}" : "{'min-width':'100%'}" }
	%nav{ "ng-style" => listing? ? "{'max-width':'75%'}" : "{'min-width':'100%'}" }
		.nav-wrapper			
			%a.brand-logo.switch.animated{ "ng-click" => "sidebarSwitch()", class: "btn-floating waves-effect waves-light btn-flat switch-{{sidebar}}" }
				= material_icon.md_24.menu.css_class "animated"
			%a.brand-logo.title.hide-on-small-only.hide-on-med-and-down
				Keppler
			= render 'layouts/admin/search'
			.actions.right				
				- if listing?
					= link_to "", { "ng-click" => "searchSiwtch()", class: "btn-floating waves-effect waves-light btn-flat hide-on-small-and-down", "ng-show" => "!inputSearch" } do
						= material_icon.md_24.search

					- if can? :destroy_multiple, model #helper
						= link_to url_for(action: :destroy_multiple, controller: controller_name).concat("?multiple_ids={{check}}#{'&search='+@query if @query}#{'&page='+@current_page if @current_page}"), method: :delete, class: "btn-floating waves-effect waves-light btn-flat tooltipped", "ng-click" => "", "ng-show"=> "btnDelete", "data-position" => "bottom", "data-tooltip" => t("keppler.actions.delete"), data: {confirm: "#{t("keppler.messages.data_confirm")}"} do
							= material_icon.md_24.delete

						- unless @objects.size.zero?
							= link_to "", class: "btn-floating waves-effect waves-light btn-flat tooltipped", "ng-click" => "selectAll(#{@objects.to_json})", "data-position" => "bottom", "data-tooltip" => t("keppler.actions.select_all") do
								%i.mi.md-24 {{iconCheck}}

					= link_to url_for(action: :index, controller: controller_name, page: @current_page, search: @query), class: "btn-floating waves-effect waves-light btn-flat spinner-refresh tooltipped hide-on-small-and-down", "ng-click" => "spinnerReload()", "data-position" => "bottom", "data-tooltip" => t("keppler.actions.refresh")  do
						= material_icon.md_24.refresh
				= link_to "#", class: "btn-floating waves-effect waves-light btn-flat dropdown-button", "data-activates" => 'more-options' do
					= material_icon.md_24.more_vert
				%ul{ id: "more-options", class: "dropdown-content" }
					%li
						= link_to t("keppler.actions.go_to_web"), main_app.root_path
					%li
						= link_to t("keppler.actions.edit_profile"), main_app.edit_user_path(current_user)
					%li.divider
					%li
						= link_to t("keppler.actions.sign_out"), main_app.destroy_user_session_path

app/views/layouts/admin/_search.html.haml
- if listing?
	= form_tag url_for(action: :index, controller: controller_name), method: :get, class: "form-search form-search-{{inputSearch}}", "ng-init" => "inputSearch=#{!@query.blank?}" do
		= text_field_tag :search, @query, class: "nav-search", placeholder: t("keppler.actions.search")
		- if @query
			= link_to url_for(action: :index, controller: controller_name), class: "hide-on-small-and-down" do
				%i.close-top-search.hide-on-small-and-down ×
		- else
			%i.close-top-search.hide-on-small-and-down{ "ng-click" => "searchSiwtch()"} ×

app/views/layouts/admin/_sidebar.html.haml
.pageslide-background{ "ng-click" => "sidebarClose()"}
	%pageslide.card{ "ps-open"=>"sidebar", "ps-auto-close" => true }
		.profile-menu{ style: @setting.appearance.image_background? ? "background: url(#{@setting.appearance.image_background}) center no-repeat; background-size: 268px 159px;" : nil  }
			.profile-pic
				= link_to "http://gravatar.com", target: "_blank" do
					= image_tag "#{(request.ssl? ? 'https://secure' : 'http://www')}.gravatar.com/avatar/#{Digest::MD5.hexdigest current_user.email}?s=60", class: "avatar"
			.profile-info
				= current_user.name
				.right
					= link_to t("keppler.actions.edit_profile"), main_app.edit_user_path(current_user)
					|
					= link_to t("keppler.actions.sign_out"), main_app.destroy_user_session_path
		%ul.pageslide-menu.collapsible{"data-collapsible" => "accordion"}
			- KepplerConfiguration.visible_models.each do |menu|
				- menu.each do |key, value|
					- unless menu[key]["submenu"] #ontetab sidebar link
						- if menu[key]["model"] #links with cancancan validate
							- if can?(:index, menu[key]["model"].constantize)
								%li
									= link_to menu[key]['url_path'], class: "collapsible-header #{'current' if menu[key]['current'].include?(controller_path)}" do
										%i.material-icons.mi.md-18= menu[key]["icon"]
										= t("keppler.menu.#{menu[key]['name']}")
						- else #links without cancancan validate
							%li
								= link_to menu[key]['url_path'], class: "collapsible-header #{'current' if menu[key]['current'].include?(controller_path)}" do
									%i.material-icons.mi.md-18= menu[key]["icon"]
									= t("keppler.menu.#{menu[key]['name']}")
					- else #tree sidebar links
						- if menu[key]["model"] && can?(:index, menu[key]["model"].constantize)
							%li
								.collapsable.collapsible-header{ class: "#{'active current' if menu[key]['current'].include?(controller_path)}" }
									%i.material-icons.mi.md-18= menu[key]['icon']
									= t("keppler.menu.#{menu[key]['name']}")
								.collapsible-body
									%ul.pageslide-sub-menu
										- menu[key]["submenu"].each do |submenu|
											- submenu.each do |name, val|
												%li
													- if settings_path?
														= link_to t("keppler.menu.#{menu[key]['name']}.submenu.#{submenu[name]['name']}"), submenu[name]['url_path'], class: "#{'current' if submenu[name]['current'].include?(@render)}"
													- else
														= link_to t("keppler.menu.#{menu[key]['name']}.submenu.#{submenu[name]['name']}"), submenu[name]['url_path'], class: "#{'current' if submenu[name]['current'].include?(controller_path)}"

app/views/layouts/admin/application.html.haml
!!!
%html
	= render "layouts/admin/head"
	%body{ 'ng-controller'=>'MainCtrl', class: "#{@setting.appearance.theme_name}-theme" }
		.waiting
			= preloader

		- if loggedin?
			= render 'layouts/admin/sidebar'
			= render 'layouts/admin/navigation'
			= render 'layouts/admin/header'
			= render 'layouts/admin/messages'
			%main.row.admin{ role: 'main', "ng-click" => "sidebarClose()" }
				= yield
		- else
			%main.devise{ style: @setting.appearance.image_background? ? "background-image: url(#{@setting.appearance.image_background})" : nil  }
				= yield